platform :ios, '8.0'
use_frameworks!
target 'ZSTestSwift’ do
    inhibit_all_warnings! #pod的工程不显示任何警告

     pod 'SnapKit', '~> 3.2.0'         #自动布局类


end

#post_install do |installer|
#    installer.pods_project.targets.each do |target|
 #       target.build_configurations.each do |config|
 #           config.build_settings['SWIFT_VERSION'] = '3.0'
#        end
  #  end
#end

